# Environment specific security groups
environments:
- staging
security_groups: 
- name: ec2::ssh
  vpc_id: <% env.vpc_id %>
  ingress:
  - protocol: tcp
    from_port: 22
    to_port: 22
    cidr_blocks:
    - 10.0.0.0/8
  egress:
  - protocol: -1
    from_port: 0
    to_port: 0
    cidr_blocks:
    - 0.0.0.0/0
